# Utilise une image Nginx de base
FROM nginx:alpine

# Copie tous les fichiers HTML, YAML, JS et CSS dans le répertoire nginx
COPY . /usr/share/nginx/html

# Nginx exposera le service sur le port 80 par défaut
EXPOSE 80
