name: Continuous Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: |
          cd backend
          go mod download

      - name: Lint and Build Backend
        run: |
          cd backend
          gofmt -s -w .
          staticcheck ./...
          go build -o bin/api ./cmd/api

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install and Build Frontend
        run: |
          cd frontend
          npm install
          npx eslint . --ext .ts,.tsx
          npm run build
