name: CI Testing

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: |
          cd backend
          go mod download

      - name: Lint Backend Code
        run: |
          cd backend
          gofmt -s -w .
          staticcheck ./...

      - name: Test Backend Code
        run: |
          cd backend
          go test ./...

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Lint Frontend Code
        working-directory: frontend
        run: npx eslint . --ext .ts,.tsx

      - name: Test Frontend Code
        working-directory: frontend
        run: npm run test
